### ISSUE TITLE
Delete impress.js integration

### ISSUE THREAD

**Issue by jceb** [arnehilmann/markdeck#32]
My impression is that the impress.js integration is not up to par with the revealjs integration yet. Furthermore, currently both frameworks are put in the output folder which makes the is unnecessarily big. In order to deliver a great experience I suggest to remove the impress.js integration.

**Comment by arnehilmann** [comment]
IMO the impress.js integration right now is quite okay (even better than some other impress.js generators), so I am interested in its shortcomings: Could you elaborate on the "not up to par" part a bit?

But for the second part of your issue: copying both frameworks in the output is nonsense, of course, and will be fixed in the next couple of days...

**Comment by jceb** [comment]
I guess I was misled regarding the impressjs integration. My feeling was that it's something more on the side rather that a serious attempt. You can ignore that part and focus on the framework duplication issue :-D

**Comment by jceb** [comment]
I'd actually find it really cool if everything, images, styling, framework and presentation could be compressed into a single html file that can be copied on a stick or a webserver to be presented to an audience. .. Might be worth another issue :-D

**Comment by arnehilmann** [comment]
Do you have problems with the `standalone` exporter of markdeck?

**Comment by jceb** [comment]
I haven't tried it yet. How does it work?

**Comment by arnehilmann** [comment]
In the header section of `slides.md`, define
`standalone: markdeck-example.html`
that should generate named file in the deck folder.
(beware, dragons here, aka alpha-status)
