### ISSUE TITLE
mermaid js is not working for reveal js

### ISSUE THREAD

**Issue by dmastag** [arnehilmann/markdeck#46]
In the showcase the mermaid js is not rendering
https://arnehilmann.github.io/markdeck/showcase/explain.html

![image](https://user-images.githubusercontent.com/5745805/93740094-ff897c80-fc13-11ea-874b-40011aa8cce6.png)

**Comment by arnehilmann** [comment]
Could you please try to reload the slides? does it render now?

**Comment by dmastag** [comment]
No, it does not work.
Curiously, it does work on my local build just not on your website.

**Comment by arnehilmann** [comment]
It even works on the website (after reloading the page), just not in `explain` mode... *sigh*
https://arnehilmann.github.io/markdeck/showcase/#/asciiart-mermaid
(if the graph does not show up, reload page) 
some weird javascript-loading/exec/timing problem?!

**Comment by dmastag** [comment]
ohh yeah, it works without explain
Weird

Should I close this ?

**Comment by arnehilmann** [comment]
mermaid support will be dropped in one of the next releases, that means, it is not bundled any longer with markdeck.
Reason: I find no time to analyze the problems with mermaid interacting with reveal.js. And because mermaid is used solely on the client-side, it is not strictly needed to be delivered by markdeck.

So: you can still use mermaid of course, by placing the needed files in the assets/ folder yourself.
