### ISSUE TITLE
Doc: scaffold before update-marckdeck in “how to start from scratch”

### ISSUE THREAD

**Issue by bmenant** [arnehilmann/markdeck#6]
[How to start from scratch](https://github.com/arnehilmann/markdeck#how-to-start-from-scratch) has to be scaffolded before `./update-markdeck` is run, hasn’t it?

Note: `scaffold` script calls `start` at its end, as a shortcut I guess... is it really useful?

**Comment by arnehilmann** [comment]
You are right, of course: I changed it to the just downloaded `./scaffold`.

`./start` at the end makes sense IMHO because with than you can start using markdeck with just one command. (keeps the tl;dr section short)
And I do not see a use case where you want to load all dependencies/files/... but not start to use them. But perhaps I am missing something?
